swipe:
  3:
    left:
      command: "xdotool key ctrl+alt+Up" # Switch to previous workspace
    right:
      command: "xdotool key ctrl+alt+Down" # Switch to next workspace
    up:
      command: "xdotool key super" # Activity
    down:
      command: "xdotool key XF86AudioMute" # Toggle Audio Mute
  4:
    left:
      command: "xdotool key XF86AudioPlay" # Play/Pause Media
    right:
      command: "xdotool key XF86AudioNext" # Next Song 
    up:
      command: "xdotool key XF86AudioRaiseVolume" # Raise Volume
    down:
      command: "xdotool key XF86AudioLowerVolume" # Lower Volume
pinch:
  in:
    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
  out:
    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
